use_frameworks!

target 'MGActionStageSwift_Example' do
  pod 'MGActionStageSwift/MGActionStageSwift_Extension', :path => '../'

  target 'MGActionStageSwift_Tests' do
    inherit! :search_paths
    
  end
end
