use_frameworks!

target 'MGActionStageSwift_Example' do
  pod 'MGActionStageSwift', :path => '../'

  target 'MGActionStageSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
